apiVersion: v1
kind: Service
metadata:
    name: k8s-reader
spec:
    selector:
        app: k8s-reader
    type: NodePort
    ports:
    -   nodePort: 31234
        port: 8081
        protocol: TCP
        targetPort: 8081
